# Generated by Django 4.2.13 on 2024-06-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='blog_image/')),
                ('title', models.CharField(max_length=255)),
                ('counted_views', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('login_required', models.BooleanField(default=False)),
                ('Category', models.ManyToManyField(to='blog.category')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
