# Generated by Django 4.2.13 on 2024-06-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='post_image/post_icon.jpg', upload_to='blog_image/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_image/post.jpeg', upload_to='blog_image/'),
        ),
    ]
