# Generated by Django 4.2.13 on 2024-07-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_image_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='login_required',
            new_name='login_user_required',
        ),
    ]
